### PR TITLE
Pixy_test_2

### PR DESCRIPTION
**Pull request by WilliamGunter**
This code should show that both lines are harmful.

### CODE REVIEW

**Comment by oliverklee** [comment]
Hi @WilliamGunter, thanks for the two pull requests. Could you please update the PR titles and descriptions so it's more visible what you would like to achieve with these changes? Thanks!

**Comment by WilliamGunter** [comment]
Hi Oliver,

I have updated both requests with a comment of what I am trying to show.
Also, I wanted to show that I cloned this code to my desktop and tried to
run locally.  Any idea of what I am doing wrong based on the snippet below?

Thanks,
Will Gunter

**Comment by WilliamGunter** [comment]
Here is the screen print I am referring to.  I am trying to find out what
is generating the error below.  Thanks.

**Comment by oliverklee** [comment]
@WilliamGunter Could you please use the GitHub web interface for posting to tickets? When you are using email, any attachments will be stripped, and the quoted text will be added to the ticket. Thanks!

**Comment by oliverklee** [comment]
Closing as there has been no feedback for more than two years.

**Pull request closed without merging**
